using System.CodeDom.Compiler;
using Android.Runtime;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ResourceDesigner("Autostop.Client.Android.Resource", IsApplication = true)]

namespace Autostop.Client.Android.Resources
{
    [GeneratedCode("Xamarin.Android.Build.Tasks", "1.0.0.0")]
    public class Resource
    {
        static Resource()
        {
            ResourceIdManager.UpdateIdValues();
        }

        public static void UpdateIdValues()
        {
        }

        public class Attribute
        {
            static Attribute()
            {
                ResourceIdManager.UpdateIdValues();
            }

            private Attribute()
            {
            }
        }

        public class Layout
        {
            // aapt resource value: 0x7f020000
            public const int Main = 2130837504;

            static Layout()
            {
                ResourceIdManager.UpdateIdValues();
            }

            private Layout()
            {
            }
        }

        public class String
        {
            // aapt resource value: 0x7f030000
            public const int app_name = 2130903040;

            static String()
            {
                ResourceIdManager.UpdateIdValues();
            }

            private String()
            {
            }
        }
    }
}
#pragma warning restore 1591